---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prefect-agent
  name: prefect-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prefect-agent
  template:
    metadata:
      labels:
        app: prefect-agent
    spec:
      containers:
        - args:
            - prefect agent kubernetes start
          command:
            - /bin/bash
            - -c
          env:
            - name: PREFECT__CLOUD__AGENT__AUTH_TOKEN
              value: ''
            - name: PREFECT__CLOUD__API
              value: https://api.prefect.io
            - name: NAMESPACE
              value: default
            - name: IMAGE_PULL_SECRETS
              value: ''
            - name: PREFECT__CLOUD__AGENT__LABELS
              value: '["dask"]'
            - name: JOB_MEM_REQUEST
              value: ''
            - name: JOB_MEM_LIMIT
              value: ''
            - name: JOB_CPU_REQUEST
              value: ''
            - name: JOB_CPU_LIMIT
              value: ''
            - name: IMAGE_PULL_POLICY
              value: ''
            - name: SERVICE_ACCOUNT_NAME
              value: ''
            - name: PREFECT__BACKEND
              value: cloud
            - name: PREFECT__CLOUD__AGENT__AGENT_ADDRESS
              value: http://:8080
            - name: PREFECT__CLOUD__API_KEY
              value: your-api-key
            - name: PREFECT__CLOUD__TENANT_ID
              value: ''
          image: prefecthq/prefect:0.15.6-python3.8
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 2
            httpGet:
              path: /api/health
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 40
          name: agent
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prefect-agent-rbac
  namespace: default
rules:
  - apiGroups:
      - batch
      - extensions
    resources:
      - jobs
    verbs:
      - '*'
  - apiGroups:
      - ''
    resources:
      - events
      - pods
    verbs:
      - '*'
  - apiGroups:
      - ""  # indicates the core API group
    resources:
      - "pods/log"
    verbs:
      - "get"
      - "list"
  - apiGroups:
      - "" # indicates the core API group
    resources:
      - "services"
    verbs:
      - "get"
      - "list"
      - "watch"
      - "create"
      - "delete"
  - apiGroups:
      - "policy"  # indicates the policy API group
    resources:
      - "poddisruptionbudgets"
    verbs:
      - "get"
      - "list"
      - "watch"
      - "create"
      - "delete"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prefect-agent-rbac
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prefect-agent-rbac
subjects:
  - kind: ServiceAccount
    name: default